version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: noDoom/Dockerfile
    ports:
      - "5115:8080"
    environment:
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 